# -*- mode: ruby -*-
# vi: set ft=ruby :

# RADP Vagrant Framework - Entry Point
# See: https://github.com/xooooooooox/radp-vagrant-framework

# Locate framework library
# Priority: RADP_VF_HOME > local lib directory
radp_vf_home = ENV['RADP_VF_HOME']
lib_path = if radp_vf_home && File.exist?(File.join(radp_vf_home, 'lib', 'radp_vagrant.rb'))
             File.join(radp_vf_home, 'lib')
           elsif File.exist?(File.join(__dir__, 'lib', 'radp_vagrant.rb'))
             File.join(__dir__, 'lib')
           end

raise 'Cannot locate RADP Vagrant Framework. Set RADP_VF_HOME environment variable.' unless lib_path

$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)
require 'radp_vagrant'

Vagrant.require_version '>=1.6.0'

Vagrant.configure('2') do |vagrant_config|
  config_dir = ENV['RADP_VAGRANT_CONFIG_DIR'] || File.join(__dir__, 'config')
  RadpVagrant.configure(vagrant_config, config_dir)
end
