#!/usr/bin/env bash
# @cmd
# @desc Generate shell completion script
# @arg shell! Shell type: bash or zsh
# @arg-values shell bash zsh
# @example completion bash
# @example completion zsh
# @example completion bash >> ~/.bashrc
# @example completion zsh > ~/.zfunc/_radp-vf

cmd_completion() {
  local shell="${1:-}"

  if [[ -z "$shell" ]]; then
    radp_log_error "Shell type required (bash or zsh)"
    return 1
  fi

  case "$shell" in
    bash)
      # Generate base completion, add delegation support, then add vg dynamic completion
      radp_cli_completion_generate "$shell" \
        | _completion_add_delegation_support \
        | _completion_add_vg_dynamic
      ;;
    zsh)
      radp_cli_completion_generate "$shell" | _completion_add_vg_dynamic_zsh
      ;;
    *)
      radp_log_error "Unsupported shell: $shell (supported: bash, zsh)"
      return 1
      ;;
  esac
}

#######################################
# Add delegation support to bash completion script
# Allows other completions (e.g., homelabctl vf) to delegate to _radp_vf
#######################################
_completion_add_delegation_support() {
  # Replace the initialization block to support delegation
  sed '
    # Match the initialization block and replace it
    /^    # 兼容模式：如果 _init_completion 不存在，使用手动初始化$/,/^    fi$/ {
      /^    # 兼容模式：如果 _init_completion 不存在，使用手动初始化$/ {
        N;N;N;N;N;N;N;N;N
        c\
    # Support delegation from other completion functions (e.g., homelabctl vf)\
    # When _RADP_VF_DELEGATED is set, skip _init_completion and use pre-set COMP_* variables\
    if [[ -z "${_RADP_VF_DELEGATED:-}" ]]; then\
        # Direct invocation: use _init_completion if available\
        if type _init_completion \&>/dev/null; then\
            _init_completion || return\
        else\
            COMPREPLY=()\
            cur="${COMP_WORDS[COMP_CWORD]}"\
            prev="${COMP_WORDS[COMP_CWORD-1]}"\
            words=("${COMP_WORDS[@]}")\
            cword="$COMP_CWORD"\
        fi\
    else\
        # Delegated invocation: use pre-set COMP_* variables\
        COMPREPLY=()\
        cur="${COMP_WORDS[COMP_CWORD]}"\
        prev="${COMP_WORDS[COMP_CWORD-1]}"\
        words=("${COMP_WORDS[@]}")\
        cword="$COMP_CWORD"\
    fi
      }
    }
  '
}

#######################################
# Add dynamic completion for vg command (bash)
# Supports: --cluster, --guest-ids option values and machine names
#######################################
_completion_add_vg_dynamic() {
  # Insert helper functions and modify the vg case
  # Use awk for more precise multi-line replacement
  awk '
    # Print helper functions after the framework comment
    /^# Generated by radp-bash-framework$/ {
      print
      print ""
      print "# Helper: Resolve config directory for completion"
      print "_radp_vf_comp_config_dir() {"
      print "    local config_dir=\"\""
      print "    local i"
      print "    for ((i = 1; i < ${#COMP_WORDS[@]}; i++)); do"
      print "        case \"${COMP_WORDS[i]}\" in"
      print "            -c|--config)"
      print "                config_dir=\"${COMP_WORDS[i+1]}\""
      print "                break"
      print "                ;;"
      print "            -c=*|--config=*)"
      print "                config_dir=\"${COMP_WORDS[i]#*=}\""
      print "                break"
      print "                ;;"
      print "        esac"
      print "    done"
      print "    if [[ -z \"$config_dir\" ]]; then"
      print "        config_dir=\"${RADP_VAGRANT_CONFIG_DIR:-}\""
      print "    fi"
      print "    if [[ -z \"$config_dir\" && -f \"./vagrant.yaml\" ]]; then"
      print "        config_dir=\".\""
      print "    fi"
      print "    [[ -n \"$config_dir\" ]] && echo \"$config_dir\""
      print "}"
      print ""
      print "# Helper: Get env override from command line"
      print "_radp_vf_comp_env() {"
      print "    local i"
      print "    for ((i = 1; i < ${#COMP_WORDS[@]}; i++)); do"
      print "        case \"${COMP_WORDS[i]}\" in"
      print "            -e|--env)"
      print "                echo \"${COMP_WORDS[i+1]}\""
      print "                return"
      print "                ;;"
      print "            -e=*|--env=*)"
      print "                echo \"${COMP_WORDS[i]#*=}\""
      print "                return"
      print "                ;;"
      print "        esac"
      print "    done"
      print "    echo \"${RADP_VAGRANT_ENV:-}\""
      print "}"
      print ""
      print "# Helper: Get cluster value from command line"
      print "_radp_vf_comp_cluster() {"
      print "    local i"
      print "    for ((i = 1; i < ${#COMP_WORDS[@]}; i++)); do"
      print "        case \"${COMP_WORDS[i]}\" in"
      print "            -C|--cluster)"
      print "                echo \"${COMP_WORDS[i+1]}\""
      print "                return"
      print "                ;;"
      print "            -C=*|--cluster=*)"
      print "                echo \"${COMP_WORDS[i]#*=}\""
      print "                return"
      print "                ;;"
      print "        esac"
      print "    done"
      print "}"
      print ""
      print "# Helper: Call Ruby completion CLI"
      print "_radp_vf_ruby_completion() {"
      print "    local config_dir=\"$1\""
      print "    local env_override=\"$2\""
      print "    local type=\"$3\""
      print "    local cluster=\"${4:-}\""
      print "    "
      print "    local radp_vf_home=\"${RADP_VF_HOME:-}\""
      print "    local ruby_lib_dir=\"\""
      print "    "
      print "    # Auto-detect radp-vf location"
      print "    if [[ -z \"$radp_vf_home\" ]]; then"
      print "        local script_path"
      print "        script_path=\"$(command -v radp-vf 2>/dev/null)\""
      print "        if [[ -n \"$script_path\" ]]; then"
      print "            # Resolve symlinks: try realpath, readlink -f, or fallback to basic readlink"
      print "            local resolved"
      print "            resolved=\"$(realpath \"$script_path\" 2>/dev/null)\" ||"
      print "            resolved=\"$(readlink -f \"$script_path\" 2>/dev/null)\" ||"
      print "            resolved=\"$script_path\""
      print "            radp_vf_home=\"$(cd \"$(dirname \"$resolved\")/..\" 2>/dev/null && pwd)\""
      print "        fi"
      print "    fi"
      print "    "
      print "    # Detect Ruby lib directory"
      print "    if [[ -d \"${radp_vf_home}/src/main/ruby/lib/radp_vagrant\" ]]; then"
      print "        ruby_lib_dir=\"${radp_vf_home}/src/main/ruby\""
      print "    elif [[ -d \"${radp_vf_home}/lib/radp_vagrant\" ]]; then"
      print "        ruby_lib_dir=\"${radp_vf_home}\""
      print "    else"
      print "        return 1"
      print "    fi"
      print "    "
      print "    # Expand tilde before processing"
      print "    if [[ \"$config_dir\" == \047~\047* ]]; then"
      print "        config_dir=\"${config_dir/#\\~/$HOME}\""
      print "    fi"
      print "    # Convert relative config_dir to absolute"
      print "    if [[ -n \"$config_dir\" && \"$config_dir\" != /* ]]; then"
      print "        config_dir=\"$(cd \"$config_dir\" 2>/dev/null && pwd)\" || return 1"
      print "    fi"
      print "    "
      print "    (cd \"$ruby_lib_dir\" && ruby -r ./lib/radp_vagrant -e \""
      print "        cmd = RadpVagrant::CLI::Completion.new("
      print "            ARGV[0],"
      print "            env_override: ARGV[1].empty? ? nil : ARGV[1],"
      print "            type: ARGV[2],"
      print "            cluster: ARGV[3].empty? ? nil : ARGV[3]"
      print "        )"
      print "        cmd.execute"
      print "    \" -- \"$config_dir\" \"$env_override\" \"$type\" \"$cluster\" 2>/dev/null)"
      print "}"
      next
    }

    # Replace vg case block - match vg and vg *
    /^        .vg.)$/ {
      in_vg = 1
      print "        \047vg\047*)"
      print "            # Dynamic completion for vg command"
      print "            local config_dir env_override cluster_val"
      print "            config_dir=\"$(_radp_vf_comp_config_dir)\""
      print "            env_override=\"$(_radp_vf_comp_env)\""
      print "            "
      print "            # Check if completing option value (space-separated form: -C xxx)"
      print "            case \"$prev\" in"
      print "                -C|--cluster)"
      print "                    if [[ -n \"$config_dir\" ]]; then"
      print "                        local clusters"
      print "                        clusters=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"clusters\")\""
      print "                        COMPREPLY=($(compgen -W \"$clusters\" -- \"$cur\"))"
      print "                    fi"
      print "                    return"
      print "                    ;;"
      print "                -G|--guest-ids)"
      print "                    cluster_val=\"$(_radp_vf_comp_cluster)\""
      print "                    if [[ -n \"$config_dir\" && -n \"$cluster_val\" ]]; then"
      print "                        cluster_val=\"${cluster_val%%,*}\""
      print "                        local guest_ids"
      print "                        guest_ids=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"guests\" \"$cluster_val\")\""
      print "                        COMPREPLY=($(compgen -W \"$guest_ids\" -- \"$cur\"))"
      print "                    fi"
      print "                    return"
      print "                    ;;"
      print "                -c|--config|-e|--env)"
      print "                    return"
      print "                    ;;"
      print "            esac"
      print "            "
      print "            # Check if completing option value (equals form: --cluster=xxx)"
      print "            case \"$cur\" in"
      print "                -C=*|--cluster=*)"
      print "                    if [[ -n \"$config_dir\" ]]; then"
      print "                        local prefix=\"${cur%%=*}=\""
      print "                        local typed=\"${cur#*=}\""
      print "                        local clusters"
      print "                        clusters=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"clusters\")\""
      print "                        COMPREPLY=($(compgen -P \"$prefix\" -W \"$clusters\" -- \"$typed\"))"
      print "                    fi"
      print "                    return"
      print "                    ;;"
      print "                -G=*|--guest-ids=*)"
      print "                    cluster_val=\"$(_radp_vf_comp_cluster)\""
      print "                    if [[ -n \"$config_dir\" && -n \"$cluster_val\" ]]; then"
      print "                        local prefix=\"${cur%%=*}=\""
      print "                        local typed=\"${cur#*=}\""
      print "                        cluster_val=\"${cluster_val%%,*}\""
      print "                        local guest_ids"
      print "                        guest_ids=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"guests\" \"$cluster_val\")\""
      print "                        COMPREPLY=($(compgen -P \"$prefix\" -W \"$guest_ids\" -- \"$typed\"))"
      print "                    fi"
      print "                    return"
      print "                    ;;"
      print "            esac"
      print "            "
      print "            # Detect vagrant subcommand position: find the first non-option word after vg"
      print "            local vg_pos=-1 vagrant_subcmd=\"\""
      print "            for ((i = 1; i < ${#words[@]}; i++)); do"
      print "                case \"${words[i]}\" in"
      print "                    -c|--config|-e|--env|-C|--cluster|-G|--guest-ids)"
      print "                        ((i++)) ;;"
      print "                    -*) ;;"
      print "                    vg)"
      print "                        vg_pos=$i ;;"
      print "                    *)"
      print "                        if [[ $vg_pos -ge 0 && -z \"$vagrant_subcmd\" ]]; then"
      print "                            vagrant_subcmd=\"${words[i]}\""
      print "                        fi"
      print "                        ;;"
      print "                esac"
      print "            done"
      print "            "
      print "            # If a vagrant subcommand was detected, try delegating to vagrant completion"
      print "            if [[ -n \"$vagrant_subcmd\" ]]; then"
      print "                if type _vagrant &>/dev/null; then"
      print "                    # Build vagrant words: skip framework options, keep vagrant args"
      print "                    local -a vagrant_words=(\"vagrant\")"
      print "                    local skip_next=false"
      print "                    for ((i = vg_pos + 1; i < ${#words[@]}; i++)); do"
      print "                        if \$skip_next; then skip_next=false; continue; fi"
      print "                        case \"${words[i]}\" in"
      print "                            -c|--config|-e|--env|-C|--cluster|-G|--guest-ids) skip_next=true ;;"
      print "                            *) vagrant_words+=(\"${words[i]}\") ;;"
      print "                        esac"
      print "                    done"
      print "                    # Save/restore COMP_* around delegation"
      print "                    local saved_comp_words=(\"${COMP_WORDS[@]}\")"
      print "                    local saved_comp_cword=$COMP_CWORD"
      print "                    local saved_comp_line=\"$COMP_LINE\""
      print "                    local saved_comp_point=$COMP_POINT"
      print "                    COMP_WORDS=(\"${vagrant_words[@]}\")"
      print "                    COMP_CWORD=$(( ${#vagrant_words[@]} - 1 ))"
      print "                    COMP_LINE=\"${vagrant_words[*]}\""
      print "                    COMP_POINT=${#COMP_LINE}"
      print "                    _vagrant 2>/dev/null"
      print "                    # Restore COMP_*"
      print "                    COMP_WORDS=(\"${saved_comp_words[@]}\")"
      print "                    COMP_CWORD=$saved_comp_cword"
      print "                    COMP_LINE=\"$saved_comp_line\""
      print "                    COMP_POINT=$saved_comp_point"
      print "                    # Augment with framework options if completing an option"
      print "                    if [[ \"$cur\" == -* ]]; then"
      print "                        COMPREPLY+=($(compgen -W \"-c --config -e --env -C --cluster -G --guest-ids\" -- \"$cur\"))"
      print "                    elif [[ -n \"$config_dir\" ]]; then"
      print "                        # Also add machine names"
      print "                        local machines"
      print "                        machines=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"machines\")\""
      print "                        if [[ -n \"$machines\" ]]; then"
      print "                            COMPREPLY+=($(compgen -W \"$machines\" -- \"$cur\"))"
      print "                        fi"
      print "                    fi"
      print "                    return"
      print "                fi"
      print "                # Fallback: no _vagrant available, offer framework options + machines"
      print "                if [[ \"$cur\" == -* ]]; then"
      print "                    COMPREPLY=($(compgen -W \"--help -c --config -e --env -C --cluster -G --guest-ids\" -- \"$cur\"))"
      print "                elif [[ -n \"$config_dir\" ]]; then"
      print "                    local machines"
      print "                    machines=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"machines\")\""
      print "                    COMPREPLY=($(compgen -W \"$machines\" -- \"$cur\"))"
      print "                fi"
      print "                return"
      print "            fi"
      print "            "
      print "            # No vagrant subcommand yet: complete vg-level options + vagrant commands + machines"
      print "            if [[ \"$cur\" == -* ]]; then"
      print "                COMPREPLY=($(compgen -W \"--help -c --config -e --env -C --cluster -G --guest-ids\" -- \"$cur\"))"
      print "            else"
      print "                local vagrant_cmds=\"box cloud connect destroy global-status halt help init login package plugin port powershell provision push rdp reload resume rsync rsync-auto serve snapshot ssh ssh-config status suspend up upload validate version winrm winrm-config\""
      print "                if [[ -n \"$config_dir\" ]]; then"
      print "                    local machines"
      print "                    machines=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"machines\")\""
      print "                    COMPREPLY=($(compgen -W \"$vagrant_cmds $machines\" -- \"$cur\"))"
      print "                else"
      print "                    COMPREPLY=($(compgen -W \"$vagrant_cmds\" -- \"$cur\"))"
      print "                fi"
      print "            fi"
      print "            ;;"
      next
    }

    # Skip lines inside vg block until we hit ;;
    in_vg && /^            ;;$/ {
      in_vg = 0
      next
    }
    in_vg { next }

    # Print all other lines
    { print }
  '
}

#######################################
# Add dynamic completion for vg command (zsh)
#######################################
_completion_add_vg_dynamic_zsh() {
  # Use awk to add helper functions and modify _radp_vf_vg
  awk '
    # Print helper functions after the framework comment
    /^# Generated by radp-bash-framework$/ {
      print
      print ""
      print "# Helper: Resolve config directory for completion"
      print "_radp_vf_comp_config_dir() {"
      print "    local config_dir=\"\""
      print "    "
      print "    # Priority 1: Check global variable from top-level opt_args"
      print "    # (set by _radp_vf when it processes -c/--config before entering subcommand)"
      print "    if [[ -n \"${_RADP_VF_OPT_CONFIG:-}\" ]]; then"
      print "        config_dir=\"$_RADP_VF_OPT_CONFIG\""
      print "    fi"
      print "    "
      print "    # Priority 2: Search words array (for subcommand-level -c/--config)"
      print "    if [[ -z \"$config_dir\" ]]; then"
      print "        local i"
      print "        for ((i = 1; i < ${#words[@]}; i++)); do"
      print "            case \"${words[i]}\" in"
      print "                -c|--config)"
      print "                    config_dir=\"${words[i+1]}\""
      print "                    break"
      print "                    ;;"
      print "                -c=*|--config=*)"
      print "                    config_dir=\"${words[i]#*=}\""
      print "                    break"
      print "                    ;;"
      print "            esac"
      print "        done"
      print "    fi"
      print "    "
      print "    # Priority 3: Environment variable"
      print "    if [[ -z \"$config_dir\" ]]; then"
      print "        config_dir=\"${RADP_VAGRANT_CONFIG_DIR:-}\""
      print "    fi"
      print "    "
      print "    # Priority 4: Current directory if it has vagrant.yaml"
      print "    if [[ -z \"$config_dir\" && -f \"./vagrant.yaml\" ]]; then"
      print "        config_dir=\".\""
      print "    fi"
      print "    [[ -n \"$config_dir\" ]] && echo \"$config_dir\""
      print "}"
      print ""
      print "# Helper: Get env override from command line"
      print "_radp_vf_comp_env() {"
      print "    # Priority 1: Check global variable from top-level opt_args"
      print "    if [[ -n \"${_RADP_VF_OPT_ENV:-}\" ]]; then"
      print "        echo \"$_RADP_VF_OPT_ENV\""
      print "        return"
      print "    fi"
      print "    "
      print "    # Priority 2: Search words array (for subcommand-level -e/--env)"
      print "    local i"
      print "    for ((i = 1; i < ${#words[@]}; i++)); do"
      print "        case \"${words[i]}\" in"
      print "            -e|--env)"
      print "                echo \"${words[i+1]}\""
      print "                return"
      print "                ;;"
      print "            -e=*|--env=*)"
      print "                echo \"${words[i]#*=}\""
      print "                return"
      print "                ;;"
      print "        esac"
      print "    done"
      print "    "
      print "    # Priority 3: Environment variable"
      print "    echo \"${RADP_VAGRANT_ENV:-}\""
      print "}"
      print ""
      print "# Helper: Get cluster value from command line"
      print "_radp_vf_comp_cluster() {"
      print "    local i"
      print "    for ((i = 1; i < ${#words[@]}; i++)); do"
      print "        case \"${words[i]}\" in"
      print "            -C|--cluster)"
      print "                echo \"${words[i+1]}\""
      print "                return"
      print "                ;;"
      print "            -C=*|--cluster=*)"
      print "                echo \"${words[i]#*=}\""
      print "                return"
      print "                ;;"
      print "        esac"
      print "    done"
      print "}"
      print ""
      print "# Helper: Call Ruby completion CLI"
      print "_radp_vf_ruby_completion() {"
      print "    local config_dir=\"$1\""
      print "    local env_override=\"$2\""
      print "    local type=\"$3\""
      print "    local cluster=\"${4:-}\""
      print "    "
      print "    local radp_vf_home=\"${RADP_VF_HOME:-}\""
      print "    local ruby_lib_dir=\"\""
      print "    "
      print "    # Auto-detect radp-vf location"
      print "    if [[ -z \"$radp_vf_home\" ]]; then"
      print "        local script_path"
      print "        script_path=\"$(command -v radp-vf 2>/dev/null)\""
      print "        if [[ -n \"$script_path\" ]]; then"
      print "            local resolved"
      print "            resolved=\"$(realpath \"$script_path\" 2>/dev/null)\" ||"
      print "            resolved=\"$(readlink -f \"$script_path\" 2>/dev/null)\" ||"
      print "            resolved=\"$script_path\""
      print "            radp_vf_home=\"$(cd \"$(dirname \"$resolved\")/..\" 2>/dev/null && pwd)\""
      print "        fi"
      print "    fi"
      print "    "
      print "    # Detect Ruby lib directory"
      print "    if [[ -d \"${radp_vf_home}/src/main/ruby/lib/radp_vagrant\" ]]; then"
      print "        ruby_lib_dir=\"${radp_vf_home}/src/main/ruby\""
      print "    elif [[ -d \"${radp_vf_home}/lib/radp_vagrant\" ]]; then"
      print "        ruby_lib_dir=\"${radp_vf_home}\""
      print "    else"
      print "        return 1"
      print "    fi"
      print "    "
      print "    # Expand tilde before processing"
      print "    if [[ \"$config_dir\" == \047~\047* ]]; then"
      print "        config_dir=\"${config_dir/#\\~/$HOME}\""
      print "    fi"
      print "    # Convert relative config_dir to absolute"
      print "    if [[ -n \"$config_dir\" && \"$config_dir\" != /* ]]; then"
      print "        config_dir=\"$(cd \"$config_dir\" 2>/dev/null && pwd)\" || return 1"
      print "    fi"
      print "    "
      print "    (cd \"$ruby_lib_dir\" && ruby -r ./lib/radp_vagrant -e \""
      print "        cmd = RadpVagrant::CLI::Completion.new("
      print "            ARGV[0],"
      print "            env_override: ARGV[1].empty? ? nil : ARGV[1],"
      print "            type: ARGV[2],"
      print "            cluster: ARGV[3].empty? ? nil : ARGV[3]"
      print "        )"
      print "        cmd.execute"
      print "    \" -- \"$config_dir\" \"$env_override\" \"$type\" \"$cluster\" 2>/dev/null)"
      print "}"
      print ""
      print "# Completion function for cluster names"
      print "_radp_vf_clusters() {"
      print "    local config_dir env_override clusters"
      print "    config_dir=\"$(_radp_vf_comp_config_dir)\""
      print "    env_override=\"$(_radp_vf_comp_env)\""
      print "    if [[ -n \"$config_dir\" ]]; then"
      print "        clusters=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"clusters\")\""
      print "        if [[ -n \"$clusters\" ]]; then"
      print "            local -a cluster_array"
      print "            cluster_array=(${(f)clusters})"
      print "            _describe \"cluster\" cluster_array"
      print "        fi"
      print "    fi"
      print "}"
      print ""
      print "# Completion function for guest IDs"
      print "_radp_vf_guests() {"
      print "    local config_dir env_override cluster_val guest_ids"
      print "    config_dir=\"$(_radp_vf_comp_config_dir)\""
      print "    env_override=\"$(_radp_vf_comp_env)\""
      print "    cluster_val=\"$(_radp_vf_comp_cluster)\""
      print "    if [[ -n \"$config_dir\" && -n \"$cluster_val\" ]]; then"
      print "        cluster_val=\"${cluster_val%%,*}\""
      print "        guest_ids=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"guests\" \"$cluster_val\")\""
      print "        if [[ -n \"$guest_ids\" ]]; then"
      print "            local -a guest_array"
      print "            guest_array=(${(f)guest_ids})"
      print "            _describe \"guest-id\" guest_array"
      print "        fi"
      print "    fi"
      print "}"
      print ""
      print "# Completion function for vg args (vagrant commands + machine names)"
      print "_radp_vf_vg_args() {"
      print "    local config_dir env_override machines"
      print "    config_dir=\"$(_radp_vf_comp_config_dir)\""
      print "    env_override=\"$(_radp_vf_comp_env)\""
      print "    "
      print "    local -a vagrant_cmds"
      print "    vagrant_cmds=(box cloud connect destroy global-status halt help init login package plugin port powershell provision push rdp reload resume rsync rsync-auto serve snapshot ssh ssh-config status suspend up upload validate version winrm winrm-config)"
      print "    "
      print "    if [[ -n \"$config_dir\" ]]; then"
      print "        machines=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"machines\")\""
      print "        if [[ -n \"$machines\" ]]; then"
      print "            local -a machine_array"
      print "            machine_array=(${(f)machines})"
      print "            vagrant_cmds+=(\"$machine_array[@]\")"
      print "        fi"
      print "    fi"
      print "    _describe \"command\" vagrant_cmds"
      print "}"
      print ""
      print "# Completion function for machine names (used by list command)"
      print "_radp_vf_machines() {"
      print "    local config_dir env_override machines"
      print "    config_dir=\"$(_radp_vf_comp_config_dir)\""
      print "    env_override=\"$(_radp_vf_comp_env)\""
      print "    if [[ -n \"$config_dir\" ]]; then"
      print "        machines=\"$(_radp_vf_ruby_completion \"$config_dir\" \"$env_override\" \"machines\")\""
      print "        if [[ -n \"$machines\" ]]; then"
      print "            local -a machine_array"
      print "            machine_array=(${(f)machines})"
      print "            _describe \"filter\" machine_array"
      print "        fi"
      print "    fi"
      print "}"
      next
    }

    # Replace _radp_vf_list function for dynamic completion
    # Note: -c/--config and -e/--env are app global options that must be recognized
    # for _radp_vf_comp_config_dir() to extract the config path for dynamic completion
    /^_radp_vf_list\(\) \{$/ {
      print "_radp_vf_list() {"
      print "    _arguments -s \\"
      print "        \047(-h --help)\047{-h,--help}\047[Show help]\047 \\"
      print "        \047(-c --config)\047{-c,--config}\047[Configuration directory]:dir:_files -/\047 \\"
      print "        \047(-e --env)\047{-e,--env}\047[Override environment name]:name:\047 \\"
      print "        \047(-a --all)\047{-a,--all}\047[Show all detailed info]\047 \\"
      print "        \047(-p --provisions)\047{-p,--provisions}\047[Show provisions only]\047 \\"
      print "        \047(-s --synced-folders)\047{-s,--synced-folders}\047[Show synced folders only]\047 \\"
      print "        \047(-t --triggers)\047{-t,--triggers}\047[Show triggers only]\047 \\"
      print "        \047(-S --status)\047{-S,--status}\047[Show VM runtime status]\047 \\"
      print "        \047*:filter:_radp_vf_machines\047"
      print "}"
      in_list = 1
      next
    }

    # Skip original _radp_vf_list body
    in_list && /^\}$/ {
      in_list = 0
      next
    }
    in_list { next }

    # Replace _radp_vf_vg function
    /^_radp_vf_vg\(\) \{$/ {
      print "_radp_vf_vg() {"
      print "    local context state state_descr line"
      print "    typeset -A opt_args"
      print ""
      print "    _arguments -C -s \\"
      print "        \047(-h --help)\047{-h,--help}\047[Show help]\047 \\"
      print "        \047(-c --config)\047{-c,--config}\047[Configuration directory]:dir:_files -/\047 \\"
      print "        \047(-e --env)\047{-e,--env}\047[Override environment name]:name:\047 \\"
      print "        \047(-C --cluster)\047{-C,--cluster}\047[Cluster names (comma-separated for multiple)]:names:_radp_vf_clusters\047 \\"
      print "        \047(-G --guest-ids)\047{-G,--guest-ids}\047[Guest IDs (comma-separated, requires --cluster)]:ids:_radp_vf_guests\047 \\"
      print "        \047*:: :->vagrant_args\047"
      print ""
      print "    case \"$state\" in"
      print "        vagrant_args)"
      print "            if (( $+functions[_vagrant] )); then"
      print "                words=(\"vagrant\" \"${words[@]}\")"
      print "                ((CURRENT++))"
      print "                _vagrant"
      print "            else"
      print "                _radp_vf_vg_args"
      print "            fi"
      print "            ;;"
      print "    esac"
      print "}"
      # Skip the original function body
      in_vg = 1
      next
    }

    # Skip original _radp_vf_vg body
    in_vg && /^\}$/ {
      in_vg = 0
      next
    }
    in_vg { next }

    # Print all other lines
    { print }
  '
}
