#compdef radp-vf

# Zsh completion script for radp-vf
# Generated by radp-bash-framework

_radp_vf_completion() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:shell:_files'
}

_radp_vf_dump_config() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-f --format)'{-f,--format}'[Output format: json or yaml (default: json)]:type:' \
        '(-o --output)'{-o,--output}'[Output file path]:file:' \
        '(-c --config)'{-c,--config}'[Configuration directory]:dir:' \
        '(-e --env)'{-e,--env}'[Override environment name]:name:' \
        '1:filter:_files'
}

_radp_vf_generate() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-c --config)'{-c,--config}'[Configuration directory]:dir:' \
        '(-e --env)'{-e,--env}'[Override environment name]:name:' \
        '1:output:_files'
}

_radp_vf_info() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-c --config)'{-c,--config}'[Configuration directory]:dir:' \
        '(-e --env)'{-e,--env}'[Override environment name]:name:' \
        '*:file:_files'
}

_radp_vf_init() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-t --template)'{-t,--template}'[Use a template (default: base)]:name:' \
        '(-s --set)'{-s,--set}'[<var>=<value>~ Set template variable (can be repeated)]:var:' \
        '1:dir:_files'
}

_radp_vf_list() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-a --all)'{-a,--all}'[Show all detailed info]' \
        '(-p --provisions)'{-p,--provisions}'[Show provisions only]' \
        '(-s --synced-folders)'{-s,--synced-folders}'[Show synced folders only]' \
        '(-t --triggers)'{-t,--triggers}'[Show triggers only]' \
        '(-c --config)'{-c,--config}'[Configuration directory]:dir:' \
        '(-e --env)'{-e,--env}'[Override environment name]:name:' \
        '1:filter:_files'
}

_radp_vf_template() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        command)
            local commands=(
                'list:List available project templates'
                'show:Show template details and variables'
            )
            _describe 'subcommand' commands
            ;;
        args)
            local cmd_func="_radp_vf_template_${words[1]//-/_}"
            if (( $+functions[$cmd_func] )); then
                $cmd_func
            else
                _files
            fi
            ;;
    esac
}

_radp_vf_template_list() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '*:file:_files'
}

_radp_vf_template_show() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:name:_files'
}

_radp_vf_validate() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-c --config)'{-c,--config}'[Configuration directory]:dir:' \
        '(-e --env)'{-e,--env}'[Override environment name]:name:' \
        '*:file:_files'
}

_radp_vf_version() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '*:file:_files'
}

_radp_vf_vg() {
    _arguments '(-h --help)'{-h,--help}'[Show help]' '*:args:'
}

_radp_vf() {
    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '--version[Show version]' \
        '-q' \
        '--quiet' \
        '(-v --verbose)'{-v,--verbose}'[Enable verbose output]' \
        '--debug[Enable debug output]' \
        '--config' \
        '--all' \
        '--json' \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        command)
            local commands=(
                'completion:Generate shell completion script'
                'dump-config:Dump merged configuration (use -o for file output)'
                'generate:Generate standalone Vagrantfile'
                'info:Show environment and configuration info'
                'init:Initialize a new project with sample configuration'
                'list:List clusters and guests from configuration'
                'template:Manage template'
                'validate:Validate YAML configuration files'
                'version:Show radp-vagrant-framework version'
                'vg:Run vagrant command with framework'
            )
            _describe 'command' commands
            ;;
        args)
            local cmd_func="_radp_vf_${words[1]//-/_}"
            if (( $+functions[$cmd_func] )); then
                $cmd_func
            else
                _files
            fi
            ;;
    esac
}

_radp_vf "$@"
