# Bash completion script for radp-vf
# Generated by radp-bash-framework

_radp_vf() {
    local cur prev words cword

    # Support delegation from other completion functions (e.g., homelabctl vf)
    # When _RADP_VF_DELEGATED is set, skip _init_completion and use pre-set COMP_* variables
    if [[ -z "${_RADP_VF_DELEGATED:-}" ]]; then
        # Direct invocation: use _init_completion if available
        if type _init_completion &>/dev/null; then
            _init_completion || return
        else
            COMPREPLY=()
            cur="${COMP_WORDS[COMP_CWORD]}"
            prev="${COMP_WORDS[COMP_CWORD-1]}"
            words=("${COMP_WORDS[@]}")
            cword="$COMP_CWORD"
        fi
    else
        # Delegated invocation: use pre-set COMP_* variables
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword="$COMP_CWORD"
    fi

    local i cmd_path=""

    # 构建当前命令路径
    for ((i = 1; i < cword; i++)); do
        case "${words[i]}" in
            -*) continue ;;
            *)
                if [[ -z "$cmd_path" ]]; then
                    cmd_path="${words[i]}"
                else
                    cmd_path="$cmd_path ${words[i]}"
                fi
                ;;
        esac
    done

    # Command completions
    case "$cmd_path" in
        '')
            COMPREPLY=($(compgen -W "completion dump-config generate info init list template validate version vg  -q --quiet -v --verbose --debug --config --all --json --help --version" -- "$cur"))
            ;;
        'completion')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'dump-config')
            COMPREPLY=($(compgen -W "--help -f --format -o --output -c --config -e --env" -- "$cur"))
            ;;
        'generate')
            COMPREPLY=($(compgen -W "--help -c --config -e --env" -- "$cur"))
            ;;
        'info')
            COMPREPLY=($(compgen -W "--help -c --config -e --env" -- "$cur"))
            ;;
        'init')
            COMPREPLY=($(compgen -W "--help -t --template -s --set" -- "$cur"))
            ;;
        'list')
            COMPREPLY=($(compgen -W "--help -a --all -p --provisions -s --synced-folders -t --triggers -c --config -e --env" -- "$cur"))
            ;;
        'template')
            COMPREPLY=($(compgen -W "list show  --help" -- "$cur"))
            ;;
        'template list')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'template show')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'validate')
            COMPREPLY=($(compgen -W "--help -c --config -e --env" -- "$cur"))
            ;;
        'version')
            COMPREPLY=($(compgen -W "--help" -- "$cur"))
            ;;
        'vg')
            COMPREPLY=($(compgen -W "--help -c --config -e --env" -- "$cur"))
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _radp_vf radp-vf
