#compdef radp-vf
# radp-vf zsh completion
# Generated by radp-vagrant-framework

# Subcommand functions
_radp_vf_init() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-t --template)'{-t,--template}'[Use a template]:template:(base single-node k8s-cluster)' \
        '*--set[Set template variable]:variable:' \
        '1:directory:_files -/'
}

_radp_vf_vg() {
    local -a vagrant_cmds=(
        'up:Start and provision VMs'
        'halt:Stop VMs'
        'destroy:Destroy VMs'
        'status:Show VM status'
        'ssh:SSH into VM'
        'provision:Run provisioners'
        'reload:Restart VMs'
        'suspend:Suspend VMs'
        'resume:Resume suspended VMs'
        'snapshot:Manage snapshots'
    )
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1: :->vagrant_cmd' \
        '*:: :->vagrant_args'

    case "$state" in
        vagrant_cmd)
            _describe -t commands 'vagrant command' vagrant_cmds
            ;;
        vagrant_args)
            # Let vagrant handle its own completion
            _files
            ;;
    esac
}

_radp_vf_list() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-v --verbose)'{-v,--verbose}'[Show detailed info]' \
        '--provisions[Show provisions only]' \
        '--synced-folders[Show synced folders only]' \
        '--triggers[Show triggers only]' \
        '1:filter:'
}

_radp_vf_dump_config() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-f --format)'{-f,--format}'[Output format]:format:(json yaml)' \
        '(-o --output)'{-o,--output}'[Output file]:file:_files' \
        '1:filter:'
}

_radp_vf_generate() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:output file:_files'
}

_radp_vf_validate() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

_radp_vf_info() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

_radp_vf_template() {
    local -a template_cmds=(
        'list:List available templates'
        'show:Show template details'
    )

    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1: :->subcmd' \
        '*:: :->args'

    case "$state" in
        subcmd)
            _describe -t commands 'template subcommand' template_cmds
            ;;
        args)
            local cmd_func="_radp_vf_template_${words[1]//-/_}"
            if (( $+functions[$cmd_func] )); then
                $cmd_func
            fi
            ;;
    esac
}

_radp_vf_template_list() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

_radp_vf_template_show() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:template:(base single-node k8s-cluster)'
}

_radp_vf_completion() {
    _arguments -s \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1:shell:(bash zsh)'
}

_radp_vf_version() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

_radp_vf_help() {
    _arguments -s '(-h --help)'{-h,--help}'[Show help]'
}

# Main completion function
_radp_vf() {
    local -a commands=(
        'init:Initialize a new project with sample configuration'
        'vg:Run vagrant command with framework'
        'list:List clusters and guests from configuration'
        'dump-config:Dump merged configuration'
        'generate:Generate standalone Vagrantfile'
        'validate:Validate YAML configuration files'
        'info:Show environment and configuration info'
        'template:Manage project templates'
        'completion:Generate shell completion script'
        'version:Show version'
        'help:Show help'
    )

    local context state state_descr line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '(-c --config)'{-c,--config}'[Configuration directory]:dir:_files -/' \
        '(-e --env)'{-e,--env}'[Override environment name]:env:' \
        '(-v --verbose)'{-v,--verbose}'[Enable verbose output]' \
        '--version[Show version]' \
        '1: :->command' \
        '*:: :->args'

    case "$state" in
        command)
            _describe -t commands 'command' commands
            ;;
        args)
            local cmd_func="_radp_vf_${words[1]//-/_}"
            if (( $+functions[$cmd_func] )); then
                $cmd_func
            else
                _files
            fi
            ;;
    esac
}

_radp_vf "$@"
