#!/usr/bin/env bash
set -euo pipefail

REPO_OWNER="${RADP_VF_REPO_OWNER:-xooooooooox}"
REPO_NAME="radp-vagrant-framework"
tmp_dir=""

log() {
  printf "%s\n" "$*"
}

err() {
  printf "radp-vagrant-framework install: %s\n" "$*" >&2
}

die() {
  err "$@"
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

detect_fetcher() {
  if have curl; then
    echo "curl"
    return 0
  fi
  if have wget; then
    echo "wget"
    return 0
  fi
  if have fetch; then
    echo "fetch"
    return 0
  fi
  return 1
}

fetch_url() {
  local tool="$1"
  local url="$2"
  local out="$3"

  case "${tool}" in
  curl)
    curl -fsSL "${url}" -o "${out}"
    ;;
  wget)
    wget -qO "${out}" "${url}"
    ;;
  fetch)
    fetch -qo "${out}" "${url}"
    ;;
  *)
    return 1
    ;;
  esac
}

fetch_text() {
  local tool="$1"
  local url="$2"

  case "${tool}" in
  curl)
    curl -fsSL "${url}"
    ;;
  wget)
    wget -qO- "${url}"
    ;;
  fetch)
    fetch -qo- "${url}"
    ;;
  *)
    return 1
    ;;
  esac
}

resolve_ref() {
  local manual_ref="${RADP_VF_REF:-}"
  local manual_version="${RADP_VF_VERSION:-}"

  if [[ -n "${manual_ref}" ]]; then
    echo "${manual_ref}"
    return 0
  fi

  if [[ -n "${manual_version}" ]]; then
    echo "${manual_version}"
    return 0
  fi

  local api_url="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/latest"
  local json
  json="$(fetch_text "${FETCH_TOOL}" "${api_url}" || true)"
  if [[ -z "${json}" ]]; then
    die "Failed to fetch latest release; set RADP_VF_VERSION or RADP_VF_REF."
  fi

  local tag
  tag="$(sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' <<<"${json}")"
  tag="${tag%%$'\n'*}"
  if [[ -z "${tag}" ]]; then
    die "Failed to parse latest tag; set RADP_VF_VERSION or RADP_VF_REF."
  fi
  echo "${tag}"
}

cleanup() {
  if [[ -n "${tmp_dir:-}" ]]; then
    rm -rf "${tmp_dir}"
  fi
}

create_wrapper() {
  local install_dir="$1"
  local bin_dir="$2"

  mkdir -p "${bin_dir}"

  local wrapper="${bin_dir}/radp-vf"
  cat > "${wrapper}" << WRAPPER_EOF
#!/usr/bin/env bash
# RADP Vagrant Framework CLI wrapper
# Generated by install.sh

RADP_VF_HOME="${install_dir}"
export RADP_VF_HOME

usage() {
  cat << USAGE
RADP Vagrant Framework CLI

Usage:
  radp-vf <command> [options]

Commands:
  init [dir]              Initialize a new project with sample configuration
  dump-config [filter]    Dump merged configuration (JSON)
  generate [output]       Generate standalone Vagrantfile
  version                 Show version
  help                    Show this help

Environment Variables:
  RADP_VF_HOME           Framework installation directory

Examples:
  radp-vf init myproject
  radp-vf dump-config
  radp-vf generate Vagrantfile.preview
USAGE
}

cmd_init() {
  local target_dir="\${1:-.}"
  mkdir -p "\${target_dir}"

  if [[ -f "\${target_dir}/Vagrantfile" ]]; then
    echo "Vagrantfile already exists in \${target_dir}"
    exit 1
  fi

  mkdir -p "\${target_dir}/config"

  # Create Vagrantfile
  cat > "\${target_dir}/Vagrantfile" << 'VAGRANTFILE'
# -*- mode: ruby -*-
# vi: set ft=ruby :

# RADP Vagrant Framework
# See: https://github.com/xooooooooox/radp-vagrant-framework

require_relative 'lib/radp_vagrant'

config_dir = ENV['RADP_VAGRANT_CONFIG_DIR'] || File.join(__dir__, 'config')

Vagrant.configure('2') do |config|
  RadpVagrant.configure(config, config_dir)
end
VAGRANTFILE

  # Create symlink to lib
  if [[ ! -e "\${target_dir}/lib" ]]; then
    ln -s "\${RADP_VF_HOME}/lib" "\${target_dir}/lib"
  fi

  # Create sample vagrant.yaml
  cat > "\${target_dir}/config/vagrant.yaml" << 'VAGRANT_YAML'
radp:
  env: sample
  extend:
    vagrant:
      plugins:
        - name: vagrant-hostmanager
          required: true
          options:
            enabled: true
            manage_host: true
            manage_guest: true
      config:
        common:
          # Global settings inherited by all guests
VAGRANT_YAML

  # Create sample vagrant-sample.yaml
  cat > "\${target_dir}/config/vagrant-sample.yaml" << 'VAGRANT_DEV_YAML'
radp:
  extend:
    vagrant:
      config:
        clusters:
          - name: example
            common:
              box:
                name: generic/ubuntu2204
            guests:
              - id: node-1
                provider:
                  mem: 2048
                  cpus: 2
                network:
                  private-network:
                    enabled: true
                    type: dhcp
VAGRANT_DEV_YAML

  echo "Initialized RADP Vagrant Framework project in \${target_dir}"
  echo ""
  echo "Next steps:"
  echo "  cd \${target_dir}"
  echo "  vagrant status"
}

cmd_dump_config() {
  local filter="\${1:-}"
  cd "\${RADP_VF_HOME}"
  if [[ -n "\${filter}" ]]; then
    ruby -r ./lib/radp_vagrant -e "RadpVagrant.dump_config('config', '\${filter}')"
  else
    ruby -r ./lib/radp_vagrant -e "RadpVagrant.dump_config('config')"
  fi
}

cmd_generate() {
  local output="\${1:-}"
  cd "\${RADP_VF_HOME}"
  if [[ -n "\${output}" ]]; then
    ruby -r ./lib/radp_vagrant -e "RadpVagrant.generate_vagrantfile('config', '\${output}')"
  else
    ruby -r ./lib/radp_vagrant -e "puts RadpVagrant.generate_vagrantfile('config')"
  fi
}

cmd_version() {
  cd "\${RADP_VF_HOME}"
  ruby -r ./lib/radp_vagrant -e "puts RadpVagrant::VERSION"
}

case "\${1:-help}" in
  init)
    shift
    cmd_init "\$@"
    ;;
  dump-config|dump_config)
    shift
    cmd_dump_config "\$@"
    ;;
  generate)
    shift
    cmd_generate "\$@"
    ;;
  version|-v|--version)
    cmd_version
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    echo "Unknown command: \$1" >&2
    usage >&2
    exit 1
    ;;
esac
WRAPPER_EOF

  chmod 0755 "${wrapper}"

  # Create alias symlink
  ln -sf "${wrapper}" "${bin_dir}/radp-vagrant-framework"
}

main() {
  FETCH_TOOL="$(detect_fetcher)" || die "Requires curl, wget, or fetch."

  local install_dir="${RADP_VF_INSTALL_DIR:-$HOME/.local/lib/${REPO_NAME}}"
  local bin_dir="${RADP_VF_BIN_DIR:-$HOME/.local/bin}"
  local ref
  ref="$(resolve_ref)"

  if [[ -z "${install_dir}" || "${install_dir}" == "/" ]]; then
    die "Unsafe install dir: ${install_dir}"
  fi
  if [[ "${RADP_VF_ALLOW_ANY_DIR:-0}" != "1" ]]; then
    if [[ "$(basename "${install_dir}")" != "${REPO_NAME}" ]]; then
      die "Install dir must end with ${REPO_NAME} (set RADP_VF_ALLOW_ANY_DIR=1 to override)."
    fi
  fi

  local tar_url="https://github.com/${REPO_OWNER}/${REPO_NAME}/archive/${ref}.tar.gz"
  tmp_dir="$(mktemp -d 2>/dev/null || mktemp -d -t "${REPO_NAME}")"
  local tarball="${tmp_dir}/${REPO_NAME}.tar.gz"
  trap cleanup EXIT

  log "Downloading ${tar_url}"
  if ! fetch_url "${FETCH_TOOL}" "${tar_url}" "${tarball}"; then
    die "Failed to download ${tar_url}"
  fi

  local tar_listing
  tar_listing="$(tar -tzf "${tarball}")"
  local root_dir="${tar_listing%%/*}"
  if [[ -z "${root_dir}" ]]; then
    die "Unable to read archive structure."
  fi

  tar -xzf "${tarball}" -C "${tmp_dir}"
  local src_root="${tmp_dir}/${root_dir}"
  if [[ ! -d "${src_root}/src/main/ruby/lib" ]]; then
    die "Archive layout unexpected; missing src/main/ruby/lib."
  fi

  rm -rf "${install_dir}"
  mkdir -p "${install_dir}"

  # Copy Ruby framework files
  cp -R "${src_root}/src/main/ruby/lib" "${install_dir}/"
  cp -R "${src_root}/src/main/ruby/Vagrantfile" "${install_dir}/" 2>/dev/null || true

  # Copy sample config if exists
  if [[ -d "${src_root}/src/main/ruby/config" ]]; then
    cp -R "${src_root}/src/main/ruby/config" "${install_dir}/"
  fi

  # Set permissions
  find "${install_dir}" -type f -name "*.rb" -exec chmod 0644 {} \;

  # Create CLI wrapper
  create_wrapper "${install_dir}" "${bin_dir}"

  log ""
  log "Installed to ${install_dir}"
  log ""
  log "Ensure ${bin_dir} is in your PATH:"
  log "  export PATH=\"${bin_dir}:\$PATH\""
  log ""
  log "Quick start:"
  log "  radp-vf init myproject"
  log "  cd myproject"
  log "  vagrant status"
}

main "$@"
